services:

  qwen3-8b:
    image: scitrera/dgx-spark-vllm:0.14.0-t4
    container_name: qwen3-8b
    runtime: nvidia
    ipc: host
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./models:/models
    networks:
      - qwen3-8b-net
    command: >
          vllm serve /models/nvidia/Qwen3-8B-NVFP4
          --host 0.0.0.0
          --port 8000
          --served-model-name Qwen3-8B-NVFP4
          --dtype auto
          --gpu-memory-utilization 0.9
          --max-model-len 22000
          --trust-remote-code
          --enable-auto-tool-choice
          --tool-call-parser qwen3_coder
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  claude-proxy:
    build:
      context: .
      dockerfile: claude-proxy.Dockerfile
    container_name: claude-code-proxy
    restart: unless-stopped
    ports:
      - "8083:8083"
    networks:
      - qwen3-8b-net
    depends_on:
      - qwen3-8b
    environment:
      - HOST=0.0.0.0
      - PORT=8083
      - PREFERRED_PROVIDER=openai
      - VLLM_MAX_CTX=22000
      - OPENAI_BASE_URL=http://qwen3-8b:8000/v1
      - OPENAI_API_KEY=sk-local-spark
      - BIG_MODEL=Qwen3-8B-NVFP4
      - SMALL_MODEL=Qwen3-8B-NVFP4

networks:
  qwen3-8b-net:
    driver: bridge
